version: '3.4'
services:
  mariadb:
    image: mysql:8.0 # mariadb:11.5.2
    ports:
      - "13306:3306"
    command:
      --init-file /data/application/db.sql
    environment:
      MYSQL_ROOT_USER: javafxTest
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: coursework
      MYSQL_USER: javafxTest
      MYSQL_PASSWORD: changeme
    volumes:
      - C:\Users\Anna\IdeaProjects\coursework\database/mariadb:/var/lib/mysql
      - C:\Users\Anna\IdeaProjects\coursework\database\db.sql:/data/application/db.sql
